@host=http://localhost:5065
@hostId=abad3e75-4dbf-4061-994b-2befa6eedf1a
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiYjY2NDU4Ny1mODM2LTQ2YTAtOTVjYy03OGZhYmJjNDBkNTAiLCJnaXZlbl9uYW1lIjoiS3lhdyIsImZhbWlseV9uYW1lIjoiWmF5YXIgVHVuIiwianRpIjoiNjI1Y2RhOGItNDFjMS00MDI0LWE4ZGItNDBkOGM1NDk0NTBkIiwiZXhwIjoxNjg2ODAyNDU2LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.YMPaOUkFw0r5eGI1l0AFBmkHEExeQBGrSMgolifgSHU

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name" : "Yummy Menu",
    "description" : "A menu with yummy food.",
    "sections" : [
        {
            "name" : "Appetizers",
            "description" : "Starters",
            "items" : [
                {
                    "name" : "Fried Pickles",
                    "description" : "Deep fried pickles."
                }
            ]
        }
    ]
}