@host=http://localhost:5065

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjMyMzE4MS0yMzFjLTQzYzItYjk5OC1lMjY4YzgwNWE1YzciLCJnaXZlbl9uYW1lIjoiS3lhdyIsImZhbWlseV9uYW1lIjoiWmF5YXIgVHVuIiwianRpIjoiNWNmNGZiMzAtN2M1Ny00N2UxLWExZWEtZmM3ZWNkZjVkZWM4IiwiZXhwIjoxNjg2NjUyODQxLCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.dI4x2vmxk_5GqsUh2bs20OJb4rvEmMyVJ-DNE4ULEnA