@host=http://localhost:5065

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1MDBmYzZiYy1jNmUwLTQyMTItYjg3Ny0zNzJlYWZlNjliYzkiLCJnaXZlbl9uYW1lIjoiS3lhdyIsImZhbWlseV9uYW1lIjoiWmF5YXIgVHVuIiwianRpIjoiYmZjZGNlZGYtYzE5Mi00OThlLTg3MWUtNzgzNzI1NDgwNDhiIiwiZXhwIjoxNjg2NzM1MzAwLCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.n6iUblDAj642abutidn44obO_QTN_kfwHwEgxrQ1-lo